import { redirect } from "next/navigation";
import { MomentButton } from "@/components/moment/MomentButton";
import { MomentCard } from "@/components/moment/MomentCard";
import { MomentPageHeader } from "@/components/moment/MomentPageHeader";
import { MomentShell } from "@/components/moment/MomentShell";
import { createSupabaseServerClient } from "@/lib/supabase/server";
async function completeOnboarding(formData: FormData) {"use server";
const supabase = await createSupabaseServerClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect('/sign-in');
const profile = { user_id:user.id, display_name:String(formData.get('display_name')??''), age_range:String(formData.get('age_range')??'18_plus'), guardian_email:String(formData.get('guardian_email')??''), focus_areas:formData.getAll('focus_areas').map(String), support_goals:formData.getAll('support_goals').map(String), onboarding_complete:true };
await supabase.from('moment_profiles').upsert(profile,{onConflict:'user_id'}); if(profile.guardian_email) await supabase.from('moment_guardian_links').upsert({student_user_id:user.id, guardian_email:profile.guardian_email},{onConflict:'student_user_id,guardian_email'}); redirect('/dashboard');}
export default async function OnboardingPage(){return <MomentShell><section className="mx-auto max-w-3xl"><MomentPageHeader eyebrow="Onboarding" title="Build your Moment baseline" subtitle="Private support for school stress, social pressure, and restart friction." /><MomentCard><form action={completeOnboarding} className="space-y-4"><input name="display_name" required placeholder="Display name" className="w-full rounded-xl bg-white/5 p-3"/><select name="age_range" className="w-full rounded-xl bg-white/5 p-3"><option value="under_13">Under 13</option><option value="13_15">13-15</option><option value="16_17">16-17</option><option value="18_plus">18+</option></select><fieldset><p className="mb-2 text-sm">What Moment helps with</p>{['school_overwhelm','social_pressure','task_start','math_stress'].map((v)=><label key={v} className="mr-4 text-sm"><input type="checkbox" name="focus_areas" value={v} className="mr-2"/>{v.replace('_',' ')}</label>)}</fieldset><fieldset><p className="mb-2 text-sm">Support goals</p>{['calmer_restarts','finish_small_tasks','protect_boundaries'].map((v)=><label key={v} className="mr-4 text-sm"><input type="checkbox" name="support_goals" value={v} className="mr-2"/>{v.replace('_',' ')}</label>)}</fieldset><input name="guardian_email" type="email" placeholder="Guardian email (optional)" className="w-full rounded-xl bg-white/5 p-3"/><p className="text-xs text-slate-400">Moment is a support tool, not therapy or crisis care. Your entries are private to your account and protected by your sign-in.</p><MomentButton type="submit">Save and continue</MomentButton></form></MomentCard></section></MomentShell>}
