import type { MomentBrainId, MomentCheckInResponse } from "@/features/ai/types";

const byBrain: Record<MomentBrainId, MomentCheckInResponse> = {
  math_reset_helper: { routeLabel: "Math Reset", routePath: "/math-reset", reflection: "Math is feeling like static right now, not a skill issue.", tinyNextStep: "Open the assignment and only read question one.", whyThisRoute: "You shared math frustration and avoidance patterns.", continueLabel: "Continue Math Reset", steps: ["Write what the problem is asking in your own words.", "Identify one known value or formula.", "Try only the first operation."], supportiveNote: "You only need one clear move to restart momentum.", followUpActions: [{ label: "Explain the math", href: "/math-reset?from=check-in" }] },
  social_boundary_helper: { routeLabel: "Boundary Pause", routePath: "/drama-pause", reflection: "You are carrying social pressure that is draining your focus.", tinyNextStep: "Pause replies for 10 minutes and choose one boundary line.", whyThisRoute: "You described relationship tension that needs boundary support.", continueLabel: "Continue Boundary Pause", steps: ["Decide what is your responsibility vs not.", "Pick a short non-escalating response.", "Mute one thread while you reset."], supportiveNote: "Protecting your energy is a smart move.", followUpActions: [{ label: "Help me stay out of it", href: "/drama-pause?from=check-in" }] },
  stuck_decomposer: { routeLabel: "Stuck Restart", routePath: "/stuck", reflection: "The task feels bigger than your current bandwidth.", tinyNextStep: "Set a five-minute timer and do the first visible action.", whyThisRoute: "You named starting friction and avoidance.", continueLabel: "Continue Stuck Restart", steps: ["Open the tab or notebook.", "Write one rough starter line.", "Stop after five minutes or continue if it feels easier."], supportiveNote: "Tiny starts are real progress.", followUpActions: [{ label: "I still feel stuck", href: "/stuck?from=check-in" }] },
  shutdown_recovery: { routeLabel: "Emotional Reset", routePath: "/check-in", reflection: "Your system sounds overloaded and low on fuel.", tinyNextStep: "Drink water, stand up, and take three slow breaths.", whyThisRoute: "You described freeze or shutdown energy.", continueLabel: "Continue Emotional Reset", steps: ["Reduce noise or visual clutter.", "Pick one single next action.", "Work for only three minutes."], supportiveNote: "Reset first, then effort.", followUpActions: [{ label: "Start a five-minute reset", href: "/check-in?from=check-in" }] },
  confidence_repair: { routeLabel: "Emotional Reset", routePath: "/check-in", reflection: "This sounds like a confidence hit, not proof you can't do it.", tinyNextStep: "Write one thing you do understand.", whyThisRoute: "Moment detected confidence strain language.", continueLabel: "Continue Emotional Reset", steps: ["Name the fear in one sentence.", "Choose a tiny school restart task.", "Finish one small proof-of-progress."], supportiveNote: "You are rebuildable, one rep at a time.", followUpActions: [{ label: "Break this down", href: "/stuck?from=check-in" }] },
  emotion_reflector: { routeLabel: "Emotional Reset", routePath: "/check-in", reflection: "You're carrying a lot, and it makes sense this feels heavy.", tinyNextStep: "Name the next 10-minute action only.", whyThisRoute: "Moment used the general support route.", continueLabel: "Continue Emotional Reset", steps: ["Pick one task.", "Reduce scope.", "Begin before motivation shows up."], supportiveNote: "You're not behind; you're restarting.", followUpActions: [{ label: "Start a five-minute reset", href: "/stuck?from=check-in" }] },
  focus_reentry: { routeLabel: "Emotional Reset", routePath: "/check-in", reflection: "", tinyNextStep: "", whyThisRoute: "", continueLabel: "Continue", steps: [], supportiveNote: "", followUpActions: [] },
  task_simplifier: { routeLabel: "Stuck Restart", routePath: "/stuck", reflection: "", tinyNextStep: "", whyThisRoute: "", continueLabel: "Continue", steps: [], supportiveNote: "", followUpActions: [] },
  school_restart: { routeLabel: "Stuck Restart", routePath: "/stuck", reflection: "", tinyNextStep: "", whyThisRoute: "", continueLabel: "Continue", steps: [], supportiveNote: "", followUpActions: [] },
  parent_summary_generator: { routeLabel: "Emotional Reset", routePath: "/parent", reflection: "", tinyNextStep: "", whyThisRoute: "", continueLabel: "Continue", steps: [], supportiveNote: "", followUpActions: [] },
  safety_classifier: { routeLabel: "Emotional Reset", routePath: "/check-in", reflection: "", tinyNextStep: "", whyThisRoute: "", continueLabel: "Continue", steps: [], supportiveNote: "", followUpActions: [] },
};

export function getMockResponse(brain: MomentBrainId): MomentCheckInResponse {
  return byBrain[brain] ?? byBrain.emotion_reflector;
}
