import type { MomentBrainId, MomentCheckInResponse } from "@/features/ai/types";

const byBrain: Record<MomentBrainId, MomentCheckInResponse> = {
  school_overwhelm_brain: { routeLabel: "School Overwhelm", routePath: "/check-in", reflection: "School pressure is heavy right now.", tinyNextStep: "Open one assignment and do the first visible action.", whyThisRoute: "You shared school overload signals.", continueLabel: "Continue School Overwhelm", steps: ["Pick one class only.", "Define a 5-minute start.", "Stop or continue after 5 minutes."], supportiveNote: "Small starts count.", followUpActions: [{ label: "Back to dashboard", href: "/dashboard" }] },
  math_reset_brain: { routeLabel: "Math Reset", routePath: "/math-reset", reflection: "Math feels noisy, not impossible.", tinyNextStep: "Read question one and rewrite it in your own words.", whyThisRoute: "Math friction detected.", continueLabel: "Continue Math Reset", steps: ["Find known values.", "Pick one operation.", "Do only the first step."], supportiveNote: "Clarity first, speed second.", followUpActions: [{ label: "Open Math Reset", href: "/math-reset" }] },
  social_boundary_brain: { routeLabel: "Social Boundary", routePath: "/drama-pause", reflection: "Social tension is draining your energy.", tinyNextStep: "Pause replies for 10 minutes.", whyThisRoute: "Boundary support signals detected.", continueLabel: "Continue Social Boundary", steps: ["Name your boundary.", "Write one calm line.", "Mute one thread while you reset."], supportiveNote: "Protecting your energy is wise.", followUpActions: [{ label: "Open Boundary Pause", href: "/drama-pause" }] },
  task_start_brain: { routeLabel: "Task Start", routePath: "/stuck", reflection: "Starting feels heavier than it should.", tinyNextStep: "Set a 5-minute timer and do the first visible action.", whyThisRoute: "Task-start friction detected.", continueLabel: "Continue Task Start", steps: ["Open the task.", "Write a rough first line.", "Continue only if easier."], supportiveNote: "Momentum grows from tiny starts.", followUpActions: [{ label: "Open Stuck", href: "/stuck" }] },
  emotional_reset_brain: { routeLabel: "Emotional Reset", routePath: "/check-in", reflection: "You’re carrying a lot, and that makes sense.", tinyNextStep: "Take one slow breath and choose one tiny action.", whyThisRoute: "General emotional overload signals detected.", continueLabel: "Continue Emotional Reset", steps: ["Lower pressure.", "Pick one task.", "Start for two minutes."], supportiveNote: "Reset first, then effort.", followUpActions: [{ label: "Open Check In", href: "/check-in" }] },
  confidence_repair_brain: { routeLabel: "Confidence Repair", routePath: "/check-in", reflection: "This feels like a confidence dip, not a dead end.", tinyNextStep: "Write one thing you already understand.", whyThisRoute: "Confidence strain language detected.", continueLabel: "Continue Confidence Repair", steps: ["Name the fear.", "Pick a tiny proof-of-progress.", "Finish one small rep."], supportiveNote: "You can rebuild one rep at a time.", followUpActions: [{ label: "Open Check In", href: "/check-in" }] },
  work_stress_brain: { routeLabel: "Work Stress", routePath: "/check-in", reflection: "Work pressure is crowding your bandwidth.", tinyNextStep: "Choose one must-do and one can-wait.", whyThisRoute: "Work stress signals detected.", continueLabel: "Continue Work Stress", steps: ["Pick one priority.", "Define done-for-today.", "Block one focus sprint."], supportiveNote: "Clear scope lowers overload.", followUpActions: [{ label: "Open Check In", href: "/check-in" }] },
  finance_clarity_brain: { routeLabel: "Finance Clarity", routePath: "/check-in", reflection: "Money stress feels heavy and urgent.", tinyNextStep: "List fixed bills and next due dates.", whyThisRoute: "Money organization signals detected.", continueLabel: "Continue Finance Clarity", steps: ["List fixed costs.", "List flexible costs.", "Write one question to research."], supportiveNote: "Clarity beats panic.", followUpActions: [{ label: "Open Check In", href: "/check-in" }] },
  relationship_reflection_brain: { routeLabel: "Relationship Reflection", routePath: "/check-in", reflection: "This relationship tension feels draining.", tinyNextStep: "Draft one boundary sentence.", whyThisRoute: "Relationship reflection signals detected.", continueLabel: "Continue Relationship Reflection", steps: ["Name the core issue.", "Draft one calm ask.", "Pick a safe time to talk."], supportiveNote: "Calm clarity helps.", followUpActions: [{ label: "Open Check In", href: "/check-in" }] },
  household_overload_brain: { routeLabel: "Household Overload", routePath: "/check-in", reflection: "Home tasks are stacking up.", tinyNextStep: "Pick one 5-minute household task.", whyThisRoute: "Household overload signals detected.", continueLabel: "Continue Household Overload", steps: ["Choose one zone.", "Do one visible task.", "Stop at 5 minutes if needed."], supportiveNote: "Visible progress counts.", followUpActions: [{ label: "Open Check In", href: "/check-in" }] },
  life_admin_brain: { routeLabel: "Life Admin", routePath: "/check-in", reflection: "Admin tasks feel endless today.", tinyNextStep: "Open one form or appointment and do step one.", whyThisRoute: "Life admin signals detected.", continueLabel: "Continue Life Admin", steps: ["Pick one errand.", "Do first micro-step.", "Set one reminder."], supportiveNote: "Small admin wins reduce drag.", followUpActions: [{ label: "Open Check In", href: "/check-in" }] },
  decision_reset_brain: { routeLabel: "Decision Reset", routePath: "/check-in", reflection: "This decision feels heavy.", tinyNextStep: "Write two options and one tradeoff each.", whyThisRoute: "Decision friction signals detected.", continueLabel: "Continue Decision Reset", steps: ["Define the decision.", "List options.", "Pick next data point."], supportiveNote: "Decisions get easier when scoped.", followUpActions: [{ label: "Open Check In", href: "/check-in" }] },
  safety_support_brain: { routeLabel: "Emotional Reset", routePath: "/check-in", reflection: "You deserve immediate support right now.", tinyNextStep: "Reach out to a trusted adult now.", whyThisRoute: "Safety signals detected.", continueLabel: "Open Emotional Reset", steps: ["Tell a trusted adult exactly what is happening.", "If immediate danger, contact emergency services."], supportiveNote: "You matter and you are not alone.", followUpActions: [{ label: "Open Check In", href: "/check-in" }] },
};

export function getMockResponse(brain: MomentBrainId): MomentCheckInResponse {
  return byBrain[brain] ?? byBrain.emotional_reset_brain;
}
