import { systemPrompts } from "@/features/ai/brains/prompts";
import type { MomentBrain, MomentBrainId } from "@/features/ai/brains/types";

const defaultSafety = ["No diagnosis or therapy claims.","No medical advice.","No financial or legal advice.","No crisis counseling.","No romantic or sexual roleplay.","No manipulation advice.","No parent surveillance of minors' private entries."];
const teenAges = ["under_13", "13_15", "16_17"] as const;
const adultTerms = ["finances", "partner", "marriage", "taxes", "workplace", "dating"];

export const brainRegistry: Record<MomentBrainId, MomentBrain> = {
  school_overwhelm_brain: { id: "school_overwhelm_brain", label: "School Reset", audience: "teen", allowedAgeRanges: [...teenAges], category: "school", routePath: "/check-in", description: "Breaks school pressure into doable next moves.", safetyBoundaries: defaultSafety, inputSignals: ["school", "class", "test", "homework", "teacher"], systemPrompt: systemPrompts.school_overwhelm_brain, outputSchemaName: "moment_response_v2" },
  math_reset_brain: { id: "math_reset_brain", label: "Math Reset", audience: "all", category: "math", routePath: "/math-reset", description: "Resets math frustration into one approachable problem.", safetyBoundaries: defaultSafety, inputSignals: ["math", "algebra", "equation", "numbers"], systemPrompt: systemPrompts.math_reset_brain, outputSchemaName: "moment_response_v2" },
  social_boundary_brain: { id: "social_boundary_brain", label: "Boundary Pause", audience: "all", disallowedSignals: adultTerms, category: "social", routePath: "/drama-pause", description: "Builds healthy responses to social tension.", safetyBoundaries: [...defaultSafety, "For minors, keep relationship support to friendships, boundaries, and safe adult support."], inputSignals: ["friend", "drama", "group chat", "rumor"], systemPrompt: systemPrompts.social_boundary_brain, outputSchemaName: "moment_response_v2" },
  task_start_brain: { id: "task_start_brain", label: "Stuck Restart", audience: "all", disallowedSignals: adultTerms, category: "task", routePath: "/stuck", description: "Creates momentum when starting feels hard.", safetyBoundaries: defaultSafety, inputSignals: ["stuck", "can't start", "avoid", "procrast"], systemPrompt: systemPrompts.task_start_brain, outputSchemaName: "moment_response_v2" },
  emotional_reset_brain: { id: "emotional_reset_brain", label: "Emotional Reset", audience: "all", category: "emotion", routePath: "/check-in", description: "Stabilizes overloaded moments with grounding.", safetyBoundaries: defaultSafety, inputSignals: ["overwhelmed", "anxious", "shutdown"], systemPrompt: systemPrompts.emotional_reset_brain, outputSchemaName: "moment_response_v2" },
  confidence_repair_brain: { id: "confidence_repair_brain", label: "Confidence Repair", audience: "all", category: "confidence", routePath: "/check-in", description: "Repairs confidence drops after setbacks.", safetyBoundaries: defaultSafety, inputSignals: ["embarrassed", "failed", "ashamed"], systemPrompt: systemPrompts.confidence_repair_brain, outputSchemaName: "moment_response_v2" },
  work_stress_brain: { id: "work_stress_brain", label: "Work Reset", audience: "adult", allowedAgeRanges: ["18_plus"], category: "work", routePath: "/check-in", description: "Supports work overload and deadline pressure.", safetyBoundaries: defaultSafety, inputSignals: ["work", "boss", "job", "deadline", "burnout"], systemPrompt: systemPrompts.work_stress_brain, outputSchemaName: "moment_response_v2" },
  finance_clarity_brain: { id: "finance_clarity_brain", label: "Money Clarity", audience: "adult", allowedAgeRanges: ["18_plus"], category: "money", routePath: "/check-in", description: "Educational money organization and budgeting clarity.", safetyBoundaries: [...defaultSafety, "Finance support is educational clarity only: budgeting organization and questions to ask, not investment/tax/legal advice."], inputSignals: ["money", "bills", "budget", "debt", "taxes"], systemPrompt: systemPrompts.finance_clarity_brain, outputSchemaName: "moment_response_v2" },
  relationship_reflection_brain: { id: "relationship_reflection_brain", label: "Relationship Reflection", audience: "adult", allowedAgeRanges: ["18_plus"], category: "relationship", routePath: "/check-in", description: "Prepares calm communication and boundaries.", safetyBoundaries: [...defaultSafety, "Relationship support is reflection and communication prep only: no manipulation, obsession, explicit intimacy, or roleplay."], inputSignals: ["partner", "spouse", "dating", "breakup", "marriage"], systemPrompt: systemPrompts.relationship_reflection_brain, outputSchemaName: "moment_response_v2" },
  household_overload_brain: { id: "household_overload_brain", label: "Home Reset", audience: "adult", allowedAgeRanges: ["18_plus"], category: "household", routePath: "/check-in", description: "Sorts home responsibilities into tiny sequences.", safetyBoundaries: defaultSafety, inputSignals: ["house", "chores", "cleaning", "home"], systemPrompt: systemPrompts.household_overload_brain, outputSchemaName: "moment_response_v2" },
  life_admin_brain: { id: "life_admin_brain", label: "Life Admin Sort", audience: "adult", allowedAgeRanges: ["18_plus"], category: "life_admin", routePath: "/check-in", description: "Organizes errands, paperwork, and recurring obligations.", safetyBoundaries: defaultSafety, inputSignals: ["errands", "paperwork", "appointments", "forms"], systemPrompt: systemPrompts.life_admin_brain, outputSchemaName: "moment_response_v2" },
  decision_reset_brain: { id: "decision_reset_brain", label: "Decision Reset", audience: "adult", allowedAgeRanges: ["18_plus"], category: "decision", routePath: "/check-in", description: "Improves clarity when choices feel heavy.", safetyBoundaries: defaultSafety, inputSignals: ["decide", "choice", "uncertain"], systemPrompt: systemPrompts.decision_reset_brain, outputSchemaName: "moment_response_v2" },
  safety_support_brain: { id: "safety_support_brain", label: "Safety Support", audience: "all", category: "safety", routePath: "/check-in", description: "Handles severe safety signals with immediate support guidance.", safetyBoundaries: defaultSafety, inputSignals: ["hurt myself", "suicide", "unsafe"], systemPrompt: systemPrompts.safety_support_brain, outputSchemaName: "moment_response_v2" },
  grief_support_brain: { id: "grief_support_brain", label: "Grief Support", audience: "all", category: "grief", routePath: "/check-in", description: "Provides emotional support for grief, loss, and painful anniversaries.", safetyBoundaries: defaultSafety, inputSignals: ["grief", "died", "loss", "miss them", "anniversary"], systemPrompt: systemPrompts.grief_support_brain, outputSchemaName: "moment_response_v2" },
  emotional_presence_brain: { id: "emotional_presence_brain", label: "Emotional Presence", audience: "all", category: "emotion", routePath: "/check-in", description: "Centers emotional acknowledgment without forcing action.", safetyBoundaries: defaultSafety, inputSignals: ["sad", "hurts", "can't stop crying", "emotional pain"], systemPrompt: systemPrompts.emotional_presence_brain, outputSchemaName: "moment_response_v2" },
  loneliness_support_brain: { id: "loneliness_support_brain", label: "Loneliness Support", audience: "all", category: "loneliness", routePath: "/check-in", description: "Supports loneliness and isolation with warmth and reflection.", safetyBoundaries: defaultSafety, inputSignals: ["alone", "lonely", "isolated", "disconnected"], systemPrompt: systemPrompts.loneliness_support_brain, outputSchemaName: "moment_response_v2" },
  overwhelm_grounding_brain: { id: "overwhelm_grounding_brain", label: "Overwhelm Grounding", audience: "all", category: "overwhelm", routePath: "/check-in", description: "Provides grounding support before any structured next step.", safetyBoundaries: defaultSafety, inputSignals: ["overwhelmed", "spiraling", "flooded"], systemPrompt: systemPrompts.overwhelm_grounding_brain, outputSchemaName: "moment_response_v2" },
};
