"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { MomentButton } from "@/components/moment/MomentButton";
import { MomentCard } from "@/components/moment/MomentCard";
import { MomentTextarea } from "@/components/moment/MomentTextarea";
import type { MomentCheckInResponse, MomentRouteResult, OperationalBlock } from "@/features/ai/types";
import type { BrainAudience, BrainCategory, MomentBrainId } from "@/features/ai/brains/types";
import type { MomentGreetingOutput } from "@/features/moment/greeting/types";
import type { MomentMemorySnapshot } from "@/features/moment/memory/types";
// ... keep type defs

type SupportStyle = "calm_reflective" | "gentle_grounding" | "structured_reset" | "action_forward";
type ClarificationChoice = { id: string; label: string; };
type ClarificationPrompt = { id: string; prompt: string; choices: ClarificationChoice[] };
type FollowUpHistoryEntry = { promptId: string; choiceId: string; choiceLabel: string };
type ContinuationOption = "continue" | "pause" | "start_fresh";
const knownBrainIds: MomentBrainId[] = ["school_overwhelm_brain","math_reset_brain","social_boundary_brain","task_start_brain","emotional_reset_brain","confidence_repair_brain","work_stress_brain","finance_clarity_brain","relationship_reflection_brain","household_overload_brain","life_admin_brain","decision_reset_brain","safety_support_brain"];
const knownAudiences: BrainAudience[] = ["teen","adult","all"];
const knownCategories: BrainCategory[] = ["school","math","social","task","emotion","confidence","work","money","relationship","household","life_admin","decision","safety"];
const supportChips = ["I feel overwhelmed","I can’t focus","I feel sad","Work pressure","Money stress","I miss someone"];
const clarificationPrompts: ClarificationPrompt[] = [{ id: "overwhelmed", prompt: "What feels loudest right now?", choices: [{ id: "school", label: "school" }, { id: "work", label: "work" }, { id: "money", label: "money" }, { id: "relationships", label: "relationships" }, { id: "everything", label: "just everything" }] },{ id: "focus", prompt: "Does it feel more like:", choices: [{ id: "emotional_overwhelm", label: "emotional overwhelm" }, { id: "mental_exhaustion", label: "mental exhaustion" }, { id: "distraction", label: "distraction" }, { id: "pressure", label: "pressure to start" }] },{ id: "sad", prompt: "Do you want:", choices: [{ id: "talk", label: "space to talk" }, { id: "grounding", label: "grounding" }, { id: "unstuck", label: "help getting unstuck" }, { id: "quiet", label: "quiet support" }] }];
const safeLabel=(id:string)=>id.replace(/_brain$/,"").split("_").map((c)=>c[0].toUpperCase()+c.slice(1)).join(" ");
// keep helper funcs abbreviated
function toSafeRoute(raw: unknown): MomentRouteResult | null { if (!raw || typeof raw !== "object") return null; const route = raw as Record<string, unknown>; const rawPrimaryBrainId = typeof route.primaryBrainId === "string" ? route.primaryBrainId : typeof route.primaryBrain === "string" ? route.primaryBrain : null; const primaryBrainId = rawPrimaryBrainId && knownBrainIds.includes(rawPrimaryBrainId as MomentBrainId) ? rawPrimaryBrainId as MomentBrainId : null; if (!primaryBrainId) return null; const supportingRaw = Array.isArray(route.supportingBrainIds) ? route.supportingBrainIds : Array.isArray(route.supportingBrains) ? route.supportingBrains : []; const supportingBrainIds = supportingRaw.filter((id): id is MomentBrainId => typeof id === "string" && knownBrainIds.includes(id as MomentBrainId)); return { primaryBrainId, supportingBrainIds, routeLabel: typeof route.routeLabel === "string" ? route.routeLabel : safeLabel(primaryBrainId), routePath: typeof route.routePath === "string" ? route.routePath : "/check-in", reason: typeof route.reason === "string" ? route.reason : "Moment selected a route based on your check-in.", confidence: "medium", audience: knownAudiences.includes(route.audience as BrainAudience) ? route.audience as BrainAudience : "all", category: knownCategories.includes(route.category as BrainCategory) ? route.category as BrainCategory : "emotion" }; }
function toSafeBlocks(blocks: unknown, reflection: string, tinyNextStep: string): OperationalBlock[] { return Array.isArray(blocks) ? blocks.filter((b): b is Record<string, unknown> => !!b && typeof b === "object").map((b)=>({ type: typeof b.type === "string" ? b.type : "support", text: typeof b.text === "string" ? b.text : "" })).filter((b)=>b.text.length>0) as OperationalBlock[] : [{ type:"reflection", text:reflection},{type:"tiny_step",text:tinyNextStep}];}
function toSafeResponse(raw: unknown, route: MomentRouteResult): MomentCheckInResponse | null { if (!raw || typeof raw !== "object") return null; const response = raw as Record<string, unknown>; const reflection = typeof response.reflection === "string" ? response.reflection : "Thanks for sharing this moment."; const tinyNextStep = typeof response.tinyNextStep === "string" ? response.tinyNextStep : "Take one small step."; return { routeLabel: typeof response.routeLabel === "string" ? response.routeLabel : route.routeLabel, routePath: typeof response.routePath === "string" ? response.routePath : route.routePath, reflection, tinyNextStep, whyThisRoute: typeof response.whyThisRoute === "string" ? response.whyThisRoute : route.reason, continueLabel: typeof response.continueLabel === "string" ? response.continueLabel : `Continue with ${route.routeLabel}`, steps: [tinyNextStep], supportiveNote: "Small steps count.", followUpActions: [{ label: `Open ${route.routeLabel}`, href: route.routePath }], blocks: toSafeBlocks(response.blocks, reflection, tinyNextStep) }; }

export function DashboardClient({ greeting, memory }: { greeting: MomentGreetingOutput; memory: MomentMemorySnapshot }) {
const [memoryState,setMemoryState]=useState(memory); const [savedNote,setSavedNote]=useState<string | null>(null); const [text,setText]=useState(""); const [selectedStates,setSelectedStates]=useState<string[]>([]); const [result,setResult]=useState<{route:MomentRouteResult;response:MomentCheckInResponse}|null>(null); const [warnings,setWarnings]=useState<string[]>([]); const [continuitySummary,setContinuitySummary]=useState<string | null>(null); const [continuityCue,setContinuityCue]=useState<string | null>(null); const [continuationOptions,setContinuationOptions]=useState<ContinuationOption[]>([]); const [error,setError]=useState<string | null>(null); const [supportStyle,setSupportStyle]=useState<SupportStyle>("calm_reflective"); const [threadId]=useState(`thread_${Date.now().toString(36)}`); const [pendingPrompt,setPendingPrompt]=useState<ClarificationPrompt | null>(null); const [followUpHistory,setFollowUpHistory]=useState<FollowUpHistoryEntry[]>([]);
const personalizedOpening=useMemo(()=>{ const thread=memoryState.threads[0]; const goal=memoryState.goals[0]; const suggestion=memoryState.suggestions[0]; if (thread?.summary) return `Looks like ${thread.summary.toLowerCase()} has been showing up lately.`; if (goal?.title) return `Want to keep moving on ${goal.title}?`; if (suggestion?.suggestionText) return `Last time, this seemed useful: ${suggestion.suggestionText}.`; return "You can start small here—what feels most present right now?";},[memoryState]);
const promptFromText=useMemo(()=>{const n=`${text} ${selectedStates.join(" ")}`.toLowerCase(); if(n.includes("overwhelm")) return clarificationPrompts[0]; if(n.includes("focus")) return clarificationPrompts[1]; if(n.includes("sad")) return clarificationPrompts[2]; return null;},[selectedStates,text]);
async function runMemoryAction(action:string,id:string){ await fetch('/api/moment/memory/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id})}); setMemoryState((curr)=>({ ...curr, suggestions: action==="accept_suggestion"||action==="dismiss_suggestion" ? curr.suggestions.filter((s)=>s.id!==id) : curr.suggestions, tinyWins: action==="hide_tiny_win" ? curr.tinyWins.map((w)=>w.id===id?{...w,status:"hidden"}:w) : curr.tinyWins, threads: action==="pause_thread" ? curr.threads.map((t)=>t.id===id?{...t,status:"paused"}:t) : action==="resume_thread" ? curr.threads.map((t)=>t.id===id?{...t,status:"active"}:t) : curr.threads, goals: action==="archive_goal" ? curr.goals.filter((g)=>g.id!==id) : curr.goals }));}
async function submit(){/* same-ish */ setError(null); setWarnings([]); try { const res=await fetch('/api/ai/check-in',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,selectedStates,conversationState:{threadId,unresolvedClarification:pendingPrompt?{promptId:pendingPrompt.id,followUpHistory}:null,selectedEmotionalContext:selectedStates,inferredSupportStyle:supportStyle}})}); if(!res.ok){setError("Moment couldn't process this check-in. Please try again.");return;} const data=await res.json() as any; const safeRoute=toSafeRoute(data.route); if(!safeRoute){setError("Unexpected route format.");return;} const safeResponse=toSafeResponse(data.response,safeRoute); if(!safeResponse){setError("Unexpected response format.");return;} setResult({route:safeRoute,response:safeResponse}); setWarnings(Array.isArray(data.warnings)?data.warnings:[]); setContinuitySummary(data.response?.continuitySummary ?? null); setContinuityCue(data.response?.continuityCue ?? null); setContinuationOptions(Array.isArray(data.response?.continuationOptions)?data.response.continuationOptions:[]); if(data.memorySnapshot) setMemoryState(data.memorySnapshot); setSavedNote("Saved to your private Moment journal."); } catch { setError("Network issue."); }}
return <div className="mx-auto max-w-4xl space-y-5"><section className="rounded-[2rem] border border-white/10 bg-[radial-gradient(circle_at_14%_0%,rgba(244,200,255,0.14),transparent_38%),radial-gradient(circle_at_88%_0%,rgba(147,197,253,0.15),transparent_36%),linear-gradient(140deg,#1a1427,#111925_58%,#1a2238)] p-6"><p className="text-xs uppercase tracking-[0.2em] text-[#e8dbff]/75">{greeting.headline}</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-[#f7efe3] sm:text-4xl">Tell Moment what's going on right now.</h2><p className="mt-2 max-w-2xl text-sm text-[#d9d8e8]">{personalizedOpening}</p><MomentTextarea rows={6} value={text} onChange={(e)=>setText(e.target.value)} placeholder="Write what this moment feels like." />{/* buttons omitted */}<MomentButton onClick={submit} disabled={text.length<3}>Continue gently</MomentButton>{savedNote?<p className="mt-2 text-xs text-violet-100/70">{savedNote}</p>:null}</section><MomentCard><p className="text-xs uppercase tracking-[0.18em] text-violet-100/70">Memory · recent patterns</p><div className="mt-3 space-y-2 text-sm text-[#d2cee5]"><p>Active goals: <span className="text-[#f8f1e7]">{memoryState.goals.length}</span></p><p>Latest tiny win: <span className="text-[#f8f1e7]">{memoryState.tinyWins[0]?.winNote ?? "Not yet recorded"}</span>{memoryState.tinyWins[0]?<button onClick={()=>runMemoryAction('hide_tiny_win',memoryState.tinyWins[0].id)} className="ml-2 text-xs">hide</button>:null}</p><p>Latest suggestion: <span className="text-[#f8f1e7]">{memoryState.suggestions[0]?.suggestionText ?? "No current suggestions"}</span>{memoryState.suggestions[0]?<><button onClick={()=>runMemoryAction('accept_suggestion',memoryState.suggestions[0].id)} className="ml-2 text-xs">accept</button><button onClick={()=>runMemoryAction('dismiss_suggestion',memoryState.suggestions[0].id)} className="ml-2 text-xs">dismiss</button></>:null}</p>{memoryState.threads[0]?<p className="text-xs">Thread: {memoryState.threads[0].summary} <button onClick={()=>runMemoryAction(memoryState.threads[0].status==='active'?'pause_thread':'resume_thread',memoryState.threads[0].id)}>{memoryState.threads[0].status==='active'?'pause':'resume'}</button></p>:null}{memoryState.goals[0]?<p className="text-xs">Goal: {memoryState.goals[0].title} <button onClick={()=>runMemoryAction('archive_goal',memoryState.goals[0].id)}>archive</button></p>:null}</div></MomentCard>{result?<section><p>{result.response.reflection}</p></section>:null}<MomentCard><Link href="/check-in">Check In</Link></MomentCard></div>;
}
